import pytest
import os
import pandas as pd
from dotenv import load_dotenv

# 1. CRITICAL: Load environment variables BEFORE importing agent_logic
load_dotenv()

from manager import init_mgmt_db, get_allowed_databases, update_user_permissions
from agent_logic import run_analysis

# Ensure data directory exists for tests
TEST_DB_PATH = "data/northwind_small.sqlite"

@pytest.fixture(scope="module", autouse=True)
def setup_test_env():
    """Initialize management database before running tests."""
    if not os.path.exists("data"):
        os.makedirs("data")
    init_mgmt_db()
    yield

# --- Test 1: RBAC & Permission Logic ---
def test_user_permission_logic():
    """Demonstrates correctness of the User Restriction requirement."""
    test_user = "automated_test_user"
    
    # Grant permission
    update_user_permissions(test_user, ["northwind"])
    
    # Verify permission
    allowed_dbs = get_allowed_databases(test_user)
    assert "northwind" in allowed_dbs
    assert allowed_dbs["northwind"] == f"sqlite:///{TEST_DB_PATH}"

# --- Test 2: Agent Integration (Mocked) ---
def test_agent_functionality(mocker):
    """Demonstrates functionality of the agent using a mock to avoid API costs/errors."""
    # We mock the return value of run_analysis to test the agent's integration flow
    expected_insight = "The Northwind database contains 77 products."
    mocker.patch('agent_logic.run_analysis', return_value=expected_insight)
    
    # Execute agent logic
    result = run_analysis(f"sqlite:///{TEST_DB_PATH}", "General Query", "How many products?")
    
    assert "77" in result
    assert "Northwind" in result

# --- Test 3: Data Formatting & Correctness (CSV Export) ---
def test_csv_export_parsing():
    """Tests the correctness of the Markdown-to-CSV extraction logic."""
    # A standard Markdown table generated by an LLM
    sample_agent_output = """
    Based on the analysis, here are the top categories:
    | CategoryName | ProductCount |
    |--------------|--------------|
    | Beverages    | 12           |
    | Condiments   | 12           |
    """

    # Corrected parsing logic: 
    # 1. Filter lines with pipes
    # 2. Filter out separator lines (---)
    lines = [line.strip() for line in sample_agent_output.strip().split('\n') 
             if '|' in line and '---' not in line]
    
    # 3. Clean each cell and remove empty strings from split
    data = []
    for line in lines:
        cells = [cell.strip() for cell in line.split('|') if cell.strip()]
        data.append(cells)
    
    # Create DataFrame
    df = pd.DataFrame(data[1:], columns=data[0])

    # Verify correctness (2 rows of data, 2 columns)
    assert df.shape == (2, 2)
    assert list(df.columns) == ["CategoryName", "ProductCount"]
    assert df.iloc[0]["CategoryName"] == "Beverages"
    assert df.iloc[1]["ProductCount"] == "12"